import { SelectOptionColor } from '@/application/database-yjs';

export const SelectOptionColorMap = {
  [SelectOptionColor.OptionColor1]: '--tag-fill-01-light',
  [SelectOptionColor.OptionColor2]: '--tag-fill-02-light',
  [SelectOptionColor.OptionColor3]: '--tag-fill-03-light',
  [SelectOptionColor.OptionColor4]: '--tag-fill-04-light',
  [SelectOptionColor.OptionColor5]: '--tag-fill-05-light',
  [SelectOptionColor.OptionColor6]: '--tag-fill-06-light',
  [SelectOptionColor.OptionColor7]: '--tag-fill-07-light',
  [SelectOptionColor.OptionColor8]: '--tag-fill-08-light',
  [SelectOptionColor.OptionColor9]: '--tag-fill-09-light',
  [SelectOptionColor.OptionColor10]: '--tag-fill-10-light',
  [SelectOptionColor.OptionColor11]: '--tag-fill-01-thick',
  [SelectOptionColor.OptionColor12]: '--tag-fill-02-thick',
  [SelectOptionColor.OptionColor13]: '--tag-fill-03-thick',
  [SelectOptionColor.OptionColor14]: '--tag-fill-04-thick',
  [SelectOptionColor.OptionColor15]: '--tag-fill-05-thick',
  [SelectOptionColor.OptionColor16]: '--tag-fill-06-thick',
  [SelectOptionColor.OptionColor17]: '--tag-fill-07-thick',
  [SelectOptionColor.OptionColor18]: '--tag-fill-08-thick',
  [SelectOptionColor.OptionColor19]: '--tag-fill-09-thick',
  [SelectOptionColor.OptionColor20]: '--tag-fill-10-thick',
};

export const SelectOptionFgColorMap = {
  [SelectOptionColor.OptionColor1]: '--tag-text-01-light',
  [SelectOptionColor.OptionColor2]: '--tag-text-02-light',
  [SelectOptionColor.OptionColor3]: '--tag-text-03-light',
  [SelectOptionColor.OptionColor4]: '--tag-text-04-light',
  [SelectOptionColor.OptionColor5]: '--tag-text-05-light',
  [SelectOptionColor.OptionColor6]: '--tag-text-06-light',
  [SelectOptionColor.OptionColor7]: '--tag-text-07-light',
  [SelectOptionColor.OptionColor8]: '--tag-text-08-light',
  [SelectOptionColor.OptionColor9]: '--tag-text-09-light',
  [SelectOptionColor.OptionColor10]: '--tag-text-10-light',
  [SelectOptionColor.OptionColor11]: '--tag-text-01-thick',
  [SelectOptionColor.OptionColor12]: '--tag-text-02-thick',
  [SelectOptionColor.OptionColor13]: '--tag-text-03-thick',
  [SelectOptionColor.OptionColor14]: '--tag-text-04-thick',
  [SelectOptionColor.OptionColor15]: '--tag-text-05-thick',
  [SelectOptionColor.OptionColor16]: '--tag-text-06-thick',
  [SelectOptionColor.OptionColor17]: '--tag-text-07-thick',
  [SelectOptionColor.OptionColor18]: '--tag-text-08-thick',
  [SelectOptionColor.OptionColor19]: '--tag-text-09-thick',
  [SelectOptionColor.OptionColor20]: '--tag-text-10-thick',
};
